### ISSUE TITLE
Spacing issue 

### ISSUE THREAD

**Issue by radhe** [vishalkakadiya/facebook-albums-challenge#1]
Spacing issue 
![screen shot 2014-12-01 at 11 33 18 am 2](https://cloud.githubusercontent.com/assets/1138674/5241895/ed59ac64-794d-11e4-8ede-245946959e1d.png)

**Comment by vishalkakadiya** [comment]
Sorry, Sir but i worked for same issue now. so that is why the spacing
issue is occur. I will do this Today only.

Thank you.

**Comment by vishalkakadiya** [comment]
Sir, Issue of spacing is done check this.

On Tue, Dec 2, 2014 at 3:05 PM, Vishal Kakadiya <vishalkakadiya123@gmail.com

> wrote:
> 
> Sorry, Sir but i worked for same issue now. so that is why the spacing
> issue is occur. I will do this Today only.
> 
> Thank you.
> 
> On Mon, Dec 1, 2014 at 11:34 AM, Radhakrishnan Mudliar <

**Comment by vishalkakadiya** [comment]
Also integrated code to scrutinizer-ci.com

https://scrutinizer-ci.com/g/vishalkakadiya/facebook-albums-challenge/

**Comment by vishalkakadiya** [comment]
This is fixed now, Closing this issue.
