### ISSUE TITLE
Download Album button is not working 

### ISSUE THREAD

**Issue by radhe** [vishalkakadiya/facebook-albums-challenge#2]
When I try to download single album I get 404 message. 

![screen shot 2014-12-03 at 5 10 08 pm](https://cloud.githubusercontent.com/assets/1138674/5279861/74a7b892-7b0f-11e4-8524-d9fe91a93ec6.png)
![screen shot 2014-12-03 at 5 09 05 pm](https://cloud.githubusercontent.com/assets/1138674/5279862/74b5cffe-7b0f-11e4-90e0-37e16546005f.png)

**Comment by vishalkakadiya** [comment]
Sir, Download issue is done.

**Comment by vishalkakadiya** [comment]
Sir, Download button is now works fine, Everything is works well.

On Wed, Dec 3, 2014 at 5:25 PM, Vishal Kakadiya <vishalkakadiya123@gmail.com

> wrote:
> 
> Sir, Download issue is done.
> 
> On Wed, Dec 3, 2014 at 5:11 PM, Radhakrishnan Mudliar <

**Comment by vishalkakadiya** [comment]
This is fixed now, Closing this issue.
