### ISSUE TITLE
scrutinizer-ci.com config

### ISSUE THREAD

**Issue by radhe** [vishalkakadiya/facebook-albums-challenge#3]
https://scrutinizer-ci.com/g/vishalkakadiya/facebook-albums-challenge/

**Comment by vishalkakadiya** [comment]
Sir, in the code all issues is come from Facebook API and Zend API, my scripts is fully cleared from issue

**Comment by vishalkakadiya** [comment]
Sir, in the code all issues is come from Facebook API and Zend API, my
scripts is fully cleared from issue
